version: '3.8'

volumes:
  postgres-data:

services:
  postgres_db:
    image: postgres
    hostname: postgres_db
    container_name: postgres_db_hateoas_project
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: postgresql
    ports:
      - "5432:5432"